### PR TITLE
Example application written in Golang

### LINKED ISSUE #17: Add example client applications
Using the adapter with the DynamoDB Java client library did not work for me. Using it with
DynamoDB Go client library did, but only if I set the entire endpoint including the operation that I want to execute manually when creating a session. That surprised me (see example below). I think this code base would benefit from a couple of simple examples on how it could be used. Considering the fact that it is intended as kind of a drop-in replacement of a DynamoDB backend, I would expect to be able to use it with a client library, and not have to create and submit the JSON messages manually.

My test client currently looks like this:
```
package main

import (
	"fmt"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute"
)

func main() {
	// Create DynamoDB client for GetItem.
	svc := dynamodb.New(createGetItemSession())

	result, err := svc.GetItem(&dynamodb.GetItemInput{
		TableName: aws.String("DynamoDbTest"),
		Key: map[string]*dynamodb.AttributeValue{
			"ColFloat64": {
				N: aws.String("2.1440135556938245e-06"),
			},
		},
	})
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	fmt.Printf("%s\n", result.String())


	// Test PutItem.
	type Rec struct {
		ColFloat64 float64
		ColInt64 int64
		ColString string
		ColBytes []byte
		ColBool bool
	}

	item := Rec{
		ColFloat64: 3.14,
		ColInt64:   1000,
		ColString:  "test",
		ColBytes:   []byte{1,2,3},
		ColBool:    true,
	}
	av, err := dynamodbattribute.MarshalMap(item)
	if err != nil {
		fmt.Println("Got error marshalling new record:")
		fmt.Println(err.Error())
		return
	}
	input := &dynamodb.PutItemInput{
		Item: av,
		TableName: aws.String("DynamoDbTest"),
	}

	// Create DynamoDB client for PutItem.
	svc = dynamodb.New(createPutItemSession())
	_, err = svc.PutItem(input)
	if err != nil {
		fmt.Println("Got error calling PutItem:")
		fmt.Println(err.Error())
		return
	}
}

var creds = credentials.NewStaticCredentials("secret", "even-more-secret", "")
var region = "eu-west-1"

func createSession(url string) *session.Session {
	return session.Must(session.NewSessionWithOptions(session.Options{
		Config: aws.Config{
			Credentials: creds,
			Region: &region,
			Endpoint: aws.String(url),
		},
	}))
}

func createGetItemSession() *session.Session {
	return createSession("http://localhost:9050/v1/GetItem")
}

func createPutItemSession() *session.Session {
	return createSession("http://localhost:9050/v1/PutItem")
}
```

Carried over from PR #3 https://github.com/cloudspannerecosystem/dynamodb-adapter/pull/3#pullrequestreview-514671503

### PR DESCRIPTION
**Pull request by bgood**
Fixes #17 

This PR includes:
- A simple data model representing an eCommerce application
- Instruction on how to migrate the data from DynamoDB to Cloud Spanner using HarbourBridge
- Simple Golang application to query DynamoDB and also Cloud Spanner using the adapter

This sample application revealed a few issues, will update this PR with issues once filed.

### CODE REVIEW

File: examples/golang/main.go [hunk 1]
```diff
@@ -0,0 +1,292 @@
...
+	"github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute"
+)
+
+func main() {
+	var sessGetItem *session.Session
+	var sessQuery *session.Session
+
+	switch cmd := os.Args[1]; cmd {
+	case "spanner":
+		sessGetItem = createAdapterSession("GetItem")
```
Comment (bgood) [inline examples/golang/main.go:37]: Currently the adapter requires that a session get created for each operation that needs to be performed `GetItem`, `Query`, `PutItem`, etc.

It would be better to use the `X-Amz-Target` HTTP Header field in the `/` endpoint of the adapter to determine the operation begin requested and route appropriately .  For example `X-Amz-Target: DynamoDB_20120810.Query` could be handled by `/` and routed to the query handler in the adapter.

Comment (bgood) [reply examples/golang/main.go:37]: Captured in Issue #28

File: examples/golang/main.go [hunk 2]
```diff
@@ -0,0 +1,292 @@
...
+	}
+
+	svc := dynamodb.New(sessGetItem)
+
+	fmt.Println("Dynamo GetItem:")
+	getCustomerContactDetails(svc)
+	
+	svc = dynamodb.New(sessQuery)
+
+	fmt.Println("\nDynamo PK/SK Query:")
```
Comment (bgood) [inline examples/golang/main.go:51]: Query operations failing with JSON serialization error.

```shell
SerializationError: failed decoding JSON RPC response
	status code: 200, request id: 
caused by: JSON value is not a list (map[string]interface {}{"L":[]interface {}{map[string]interface {}{"PK":map[string]interface {}{"S":"CUST#0000000000"}, "SK":map[string]interface {}{"S":"ORDER#ej68vuldzgps"}, "customer_id":map[string]interface {}{"S":"0000000000"}, "order_id":map[string]interface {}{"S":"ej68vuldzgps"}, "order_status":map[string]interface {}{"S":"PROCESSING"}, "order_ts":map[string]interface {}{"S":"2021-05-14T12:07:00.000000"}}}})
No record foundpanic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.getCustomerOrderDetails(0xc0000b2340)
	projects/forks/dynamodb-adapter/examples/golang/main.go:115 +0x6b3
main.main()
	projects/forks/dynamodb-adapter/examples/golang/main.go:52 +0x1c5
```

Comment (bgood) [reply examples/golang/main.go:51]: Captured in Issue #29

File: examples/golang/main.go (hunk 1 above)
Comment (bgood) [reply examples/golang/main.go]: This issue has been resolved in PR #34 and has been merged into this branch.

File: examples/golang/main.go (hunk 2 above)
Comment (bgood) [reply examples/golang/main.go:46]: This issue was fixed in PR #36 and has been merged into this branch.

**Comment by bgood** [comment]
This is kind of a big one, apologies.

This PR includes:
- Sample data model built around an ecommerce use case.
- Sample application written in golang, which queries against DynamoDB and Cloud Spanner using the adapter
- Instructions on how to load the sample data, migrate using Harbourbridge and run the sample application.

File: examples/adapter/init.go [hunk 3]
```diff
@@ -0,0 +1,296 @@
+// Copyright 2020 Google LLC
```
Comment (skuruppu) [inline examples/adapter/init.go:1]:
```suggestion
// Copyright 2021 Google LLC
```

File: examples/sample-data/put_customer_order_items.py [hunk 4]
```diff
@@ -0,0 +1,186 @@
...
+# limitations under the License.
+
+from decimal import Decimal
+import boto3
+import csv
+
+dynamo = boto3.resource('dynamodb')
+
+def put_customer_item(pk, sk, customer_id, customer_fname, customer_lname, customer_email, customer_addresses):
+
```
Comment (skuruppu) [inline examples/sample-data/put_customer_order_items.py:22]:
```suggestion
```

Minor nits in this and suggestions below to remove extra newlines to be consistent with the Google Python style guide.

File: examples/sample-data/put_customer_order_items.py [hunk 5]
```diff
@@ -0,0 +1,186 @@
...
+            'customer_email': customer_email,
+            'customer_addresses': customer_addresses
+            }
+        )
+        
+    return resp
+
+
+def process_customer_items():
+
```
Comment (skuruppu) [inline examples/sample-data/put_customer_order_items.py:40]:
```suggestion
```

File: examples/sample-data/put_customer_order_items.py [hunk 6]
```diff
@@ -0,0 +1,186 @@
...
+            print('customer_lname: ' + customer_lname)
+            print('customer_email: ' + customer_email)
+            print('customer_addresses: ' + customer_addresses)
+    
+            resp = put_customer_item(pk, sk, customer_id, customer_fname, customer_lname, customer_email, customer_addresses)
+
+            print('resp: ' + str(resp))
+
+def put_order_item(pk, sk, customer_id, order_id, order_status, order_ts, order_amount, number_of_items):
+
```
Comment (skuruppu) [inline examples/sample-data/put_customer_order_items.py:70]:
```suggestion
```

File: examples/sample-data/put_customer_order_items.py [hunk 7]
```diff
@@ -0,0 +1,186 @@
...
+            'order_ts': order_ts,
+            'order_amount': order_amount,
+            'number_of_items': number_of_items
+            }
+        )
+        
+    return resp
+
+def process_order_items():
+
```
Comment (skuruppu) [inline examples/sample-data/put_customer_order_items.py:88]:
```suggestion
```

File: examples/sample-data/put_customer_order_items.py [hunk 8]
```diff
@@ -0,0 +1,186 @@
...
+            'customer_id': customer_id,
+            'customer_fname': customer_fname,
+            'customer_lname': customer_lname,
+            'customer_email': customer_email,
+            'customer_addresses': customer_addresses
+            }
+        )
+        
+    return resp
+
```
Comment (skuruppu) [inline examples/sample-data/put_customer_order_items.py:37]:
```suggestion
```

File: examples/sample-data/put_customer_order_items.py [hunk 9]
```diff
@@ -0,0 +1,186 @@
...
+            print('order_status: ' + order_status)
+            print('order_ts: ' + order_ts)
+            print('order_amount: ' + str(order_amount))
+            print('number_of_items: ' + str(number_of_items))
+            
+            resp = put_order_item(pk, sk, customer_id, order_id, order_status, order_ts, order_amount, number_of_items)
+
+            print('resp: ' + str(resp))
+
+
```
Comment (skuruppu) [inline examples/sample-data/put_customer_order_items.py:119]:
```suggestion
```

File: examples/sample-data/put_customer_order_items.py [hunk 10]
```diff
@@ -0,0 +1,186 @@
...
+def put_line_item(pk, sk, order_id, line_item_id, product_id, item_price, item_discount, item_quantity, item_status, comment):
+
```
Comment (skuruppu) [inline examples/sample-data/put_customer_order_items.py:121]:
```suggestion
```

File: examples/sample-data/put_customer_order_items.py [hunk 11]
```diff
@@ -0,0 +1,186 @@
...
+            'item_quantity': item_quantity,
+            'item_status': item_status,
+            'comment': comment
+            }
+        )
+        
+    return resp
+
+def process_line_items():
+
```
Comment (skuruppu) [inline examples/sample-data/put_customer_order_items.py:141]:
```suggestion
```

File: examples/sample-data/put_customer_order_items.py [hunk 12]
```diff
@@ -0,0 +1,186 @@
...
+def process_customer_items():
+
+    with open('data/customer.tsv', newline='') as csvfile:
+        reader = csv.reader(csvfile, delimiter='\t', quotechar='"')
+        next(reader) # skip header line
+    
+        for row in reader:
+            
+            #print('row: ' + str(row))
+
```
Comment (skuruppu) [inline examples/sample-data/put_customer_order_items.py:48]:
```suggestion
```

File: examples/sample-data/put_customer_order_items.py [hunk 13]
```diff
@@ -0,0 +1,186 @@
...
+def process_order_items():
+
+    with open('data/order.tsv', newline='') as csvfile:
+        reader = csv.reader(csvfile, delimiter='\t', quotechar='"')
+        next(reader) # skip header line
+    
+        for row in reader:
+            
+            #print('row: ' + str(row))
+
```
Comment (skuruppu) [inline examples/sample-data/put_customer_order_items.py:96]:
```suggestion
```

File: examples/sample-data/put_customer_order_items.py [hunk 14]
```diff
@@ -0,0 +1,186 @@
...
+def process_line_items():
+
+    with open('data/line_item.tsv', newline='') as csvfile:
+        reader = csv.reader(csvfile, delimiter='\t', quotechar='"')
+        next(reader) # skip header line
+    
+        for row in reader:
+            
+            #print('row: ' + str(row) + ', len: ' + str(len(row)))
+
```
Comment (skuruppu) [inline examples/sample-data/put_customer_order_items.py:149]:
```suggestion
```

File: examples/sample-data/put_product_items.py [hunk 15]
```diff
@@ -0,0 +1,151 @@
...
+# limitations under the License.
+
+from decimal import Decimal
+import boto3
+import csv
+
+dynamo = boto3.resource('dynamodb')
+
+def put_book_product_item(pk, sk, product_id, product_category, isbn, book_title, book_authors, book_format, book_publisher, publication_date, price, shipping_amount):
+
```
Comment (skuruppu) [inline examples/sample-data/put_product_items.py:22]:
```suggestion
```

File: examples/sample-data/put_product_items.py [hunk 16]
```diff
@@ -0,0 +1,151 @@
...
+            'price': price,
+            'shipping_amount': shipping_amount
+            }
+        )
+        
+    return resp
+
+
+def process_book_product_items():
+
```
Comment (skuruppu) [inline examples/sample-data/put_product_items.py:45]:
```suggestion
```

File: examples/sample-data/put_product_items.py [hunk 17]
```diff
@@ -0,0 +1,151 @@
...
+    with open('data/book_product.tsv', newline='') as csvfile:
+        reader = csv.reader(csvfile, delimiter='\t', quotechar='"')
+        next(reader) # skip header line
+    
+        for row in reader:
+            
+            #print('row: ' + str(row))
+
```
Comment (skuruppu) [inline examples/sample-data/put_product_items.py:53]:
```suggestion
```

File: examples/sample-data/put_product_items.py [hunk 18]
```diff
@@ -0,0 +1,151 @@
...
+            print('shipping_amount: ' + str(shipping_amount))
+    
+            resp = put_book_product_item(pk, sk, product_id, product_category, isbn, book_title, book_authors, book_format, book_publisher, publication_date,\
+                                    price, shipping_amount)
+
+            print('resp: ' + str(resp))
+            
+
+def put_electronic_product_item(pk, sk, product_id, product_name, product_category, price, upc, shipping_amount, product_description, manufacturer, model):
+
```
Comment (skuruppu) [inline examples/sample-data/put_product_items.py:87]:
```suggestion
```

File: examples/sample-data/put_product_items.py [hunk 19]
```diff
@@ -0,0 +1,151 @@
...
+            'product_description': product_description,
+            'manufacturer': manufacturer,
+            'model': model
+            }
+        )
+        
+    return resp
+
+def process_electronic_product_items():
+
```
Comment (skuruppu) [inline examples/sample-data/put_product_items.py:107]:
```suggestion
```

File: examples/sample-data/put_product_items.py [hunk 20]
```diff
@@ -0,0 +1,151 @@
...
+    with open('data/electronic_product.tsv', newline='') as csvfile:
+        reader = csv.reader(csvfile, delimiter='\t', quotechar='"')
+        next(reader) # skip header line
+    
+        for row in reader:
+            
+            print('row: ' + str(row))
+
```
Comment (skuruppu) [inline examples/sample-data/put_product_items.py:115]:
```suggestion
```

**Review by skuruppu — APPROVED** [review]
Feel free to ignore my suggestions on the py files if there's a reason to format it that way.
